### ISSUE TITLE
add Ulam language.

### ISSUE THREAD

**Issue by audriu** [angrykoala/awesome-esolangs#19]
Altho the creators does not think it is esoteric, but it is very like Befuge. and it is very hard to code in it...

**Comment by angrykoala** [comment]
Hi @audriu, thanks for your interest, please note that being hard to code in is not a enough for it to be an esoteric language (in fact, not all esoteric languages are necessarily hard). As far as I could see, this language was not intended as an esolang ("An esoteric programming language, or esolang, is a computer programming language designed to experiment with weird ideas, to be hard to program in, or as a joke, rather than for practical use.") and doesn't seem to fullfill any of those requirements.

I will close this issue. If you still feel this language is appropriate for this list, add a comment to this issue with reasons this could be an esoteric language and, if possible, links to resources that support these arguments

Thanks
