### ISSUE TITLE
Almost Binary

### ISSUE THREAD

**Issue by wsdt** [angrykoala/awesome-esolangs#46]
Hi, there!

What do you think of Almost Binary?
Just created this young esoteric programming language a few days ago and will improve it continuously.

[Almost Binary](https://github.com/wsdt/AlmostBinary)

**Comment by angrykoala** [comment]
Hi @wsdt

Cool language :smile:. I couldn't find info on how to write an `abin` program, not sure if docs are still a TO DO

I'm happy to add Almost Binary to the list (or feel free to send a PR) but it would be nice to have a bit of documentation on how to write a program (kinda hard to learn to code abin from the examples :laughing:)

Thanks for your contribution

**Comment by wsdt** [comment]
Hi @angrykoala 

Thank you for your fast response. 
Almost Binary has been published today. But this shouldn't be an excuse. 

I added now some more precise documentation to the wiki and will improve it while developing new features, etc.
https://github.com/wsdt/AlmostBinary/wiki

**Comment by angrykoala** [comment]
@wsdt No worries, that's understandable, my comment was because without some docs explaining a little bit on how to use an obscure language, users coming to your repo may feel a bit overwhelmed.

I've checked your new additions to the wiki and they look quite nice. I'll add this language as soon as I have some time (or, I'm happy to check a PR if you want to add it to the list yourself)

**Comment by wsdt** [comment]
Great, thank you :-)

**Comment by wsdt** [comment]
Opened a PR :-)
